name: CI

on: 
  pull_request:
  push:
    branches: [main, develop]
    tags: ['*']
    
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.arch }} - ${{ github.event_name}}
    runs-on: self-hosted
    strategy: 
      fail-fast: false
      matrix:
        version:
          # - "1.10" # LTS (64-bit Linux)
          - "1.9" 
          - '1'  # latest stable Julia release (Linux)
          # - 'nightly'
        arch:
          - x64
        # include:
        #   - version: '1'
        #     os: windows-latest
        #     arch: x64

    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@latest
      - name: Run tests 
        run: salloc -N 1 -n 1 -t 0:20:00 bash -c "module load gurobi/12.0.0; julia --color=yes --project=${{ github.workspace }} -e 'using Pkg; Pkg.test(\"MacroEnergy\")'"
      - uses: julia-actions/julia-processcoverage@v1
      # - uses: codecov/codecov-action@v3
      #   with:
      #     file: lcov.info